### ISSUE TITLE
apparent missing appropriate assembler on smartOS 16

### ISSUE THREAD

**Issue by Trott** [nodejs/reliability#6]
Should we track infra issues around CI reliability here? Because https://github.com/nodejs/build/issues/1327 has us red right now.

**Comment by refack** [comment]
Personally I'm -1.
The build WG has https://github.com/nodejs/build/projects/1 for tracking CI incidents, and all collaborators are welcome to use it to check for known infra issues.

But, this specific case is interesting since it seems to be a code regression and not nececerily an infra issue (Ref: https://github.com/nodejs/node/pull/21220).
The CI log for the change that might have caused this have been cleared, so it's hard for me to see how the infra behaved during validation...

**Comment by Trott** [comment]
Going to close this now as there are PRs to fix it and it's being tracked elsewhere as @refack points out.
